/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.HoaDonDAO;
import dao.ViecMuaHangDAO;
import java.awt.HeadlessException;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.HoaDon;
import model.KhachHang;
import model.MatHang;
import model.ViecMuaHang;

/**
 *
 * @author DatIT
 */
public class DanhSachMuaHangFrm extends javax.swing.JFrame {
    private DefaultTableModel model = new DefaultTableModel();
    private HoaDon listMuaMH;
    private boolean daLuu = false;
    /**
     * Creates new form DanhSachMuaHangFrm
     */
    
    public DanhSachMuaHangFrm() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public DanhSachMuaHangFrm(KhachHang kh) {
        initComponents();
        listMuaMH = new HoaDon();
        listMuaMH.setKhach(kh);
        themDuuLieuHoaDon();
        
        initTable();
        setLocationRelativeTo(null);
    }

    public DanhSachMuaHangFrm(HoaDon listMuaMH) {
        initComponents();
        this.listMuaMH = listMuaMH;
        
        initTable();
        setLocationRelativeTo(null);
    }

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LabTen = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblViecMuaHang = new javax.swing.JTable();
        btnLuu = new javax.swing.JButton();
        btnXoaMatHang = new javax.swing.JButton();
        btnQuayLai = new javax.swing.JButton();
        btnThemSanPham = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Danh Sách Mua Hàng");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 255));
        jLabel1.setText("PHẦN MỀM QUẢN LÝ BÁN HÀNG");

        jLabel2.setText("Tên Khách Hàng:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Danh Sách Mua Hàng:");

        LabTen.setText("\"Tên\"");

        tblViecMuaHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblViecMuaHang);

        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnXoaMatHang.setText("Xóa Mặt Hàng");
        btnXoaMatHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaMatHangActionPerformed(evt);
            }
        });

        btnQuayLai.setText("Quay Lại");
        btnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLaiActionPerformed(evt);
            }
        });

        btnThemSanPham.setText("Thêm Sản Phẩm");
        btnThemSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemSanPhamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(141, 141, 141))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(207, 207, 207))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(LabTen, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(btnThemSanPham)
                .addGap(18, 18, 18)
                .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnXoaMatHang, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnQuayLai, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(LabTen))
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLuu)
                    .addComponent(btnXoaMatHang)
                    .addComponent(btnQuayLai)
                    .addComponent(btnThemSanPham))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        if( listMuaMH.getListVMH().size() == 0){
            JOptionPane.showMessageDialog(this, "Danh sách mua hàng trống", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        // thêm hóa đơn vào CSDL trước
        HoaDonDAO hdd = new HoaDonDAO();
        hdd.themHoaDon(listMuaMH);
        
        // thêm việc mua hàng vào CSDL
        
        ViecMuaHangDAO vmhD = new ViecMuaHangDAO();
        vmhD.themViecMuaHang( listMuaMH);
        JOptionPane.showMessageDialog(this, "Lưu thành công!");
        
        (new XuatHoaDonFrm(listMuaMH)).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnXoaMatHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaMatHangActionPerformed
        int rowSelected = tblViecMuaHang.getSelectedRow();
        if( rowSelected >= 0){
            int idMatHang = (int) tblViecMuaHang.getValueAt(rowSelected, 1);
            
            for (ViecMuaHang viecMuaHang : listMuaMH.getListVMH()) {
                if( viecMuaHang.getMatHang().getId() == idMatHang){
                    int choice = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn xóa sản phẩm có mã " +
                            idMatHang, "Xác nhận", JOptionPane.YES_NO_OPTION);
                    if( choice == JOptionPane.NO_OPTION) break;
                    listMuaMH.getListVMH().remove(viecMuaHang);
                    JOptionPane.showMessageDialog(this, "Xóa thành công");
                    fillTable();
                    break;
                }
            }
            
        }
    }//GEN-LAST:event_btnXoaMatHangActionPerformed

    private void btnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaiActionPerformed
        if( !daLuu && listMuaMH.getListVMH().size() > 0){
            JOptionPane.showMessageDialog(this, "Bạn chưa lưu lại danh sách");
            return;
        }
        ( new ChonKhachHangFrm()).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQuayLaiActionPerformed

    private void btnThemSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemSanPhamActionPerformed
        
        (new ChonMatHangFrm(listMuaMH)).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnThemSanPhamActionPerformed
    
    private void initTable(){// khởi tạo 
        
        // Hien thi ten
        LabTen.setText( listMuaMH.getKhach().getHoTen());
        
        // Tạo bảng
        String[] Colums = new String[]{
            "STT", "Mã Mặt Hàng" ,"Tên", "Số Lượng" , "Ghi Chú"
        };
        model.setColumnIdentifiers(Colums);
        if( listMuaMH.getListVMH().size() == 0){
            tblViecMuaHang.setModel(model);
            
        }else{
            int index = 1;
            for (ViecMuaHang viecMuaHang : listMuaMH.getListVMH()) {
                model.addRow(new Object[]{ index++, viecMuaHang.getMatHang().getId(),
                viecMuaHang.getMatHang().getTen(), viecMuaHang.getSoLuong(), viecMuaHang.getGhiChu()});
            }
            tblViecMuaHang.setModel(model);
            
        }
            
    }
    private void fillTable(){// load lại bảng
        model.setRowCount(0);
        
        int index = 1;
        for (ViecMuaHang viecMuaHang : listMuaMH.getListVMH()) {
            model.addRow(new Object[]{ index++, viecMuaHang.getMatHang().getId(),
            viecMuaHang.getMatHang().getTen(), viecMuaHang.getSoLuong(), viecMuaHang.getGhiChu()});
        }
        model.fireTableDataChanged();
    }
    private void themDuuLieuHoaDon(){
        // đóng gói dữ liệu hóa đơn
        
        Date now = new Date();
        listMuaMH.setThoiGianMua(now);
        listMuaMH.setDaThanhToan(false);
        listMuaMH.tinhKhuyenMai();
        
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabTen;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnQuayLai;
    private javax.swing.JButton btnThemSanPham;
    private javax.swing.JButton btnXoaMatHang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tblViecMuaHang;
    // End of variables declaration//GEN-END:variables
}
