/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.TinhToanHoaDonDAO;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import javax.swing.table.DefaultTableModel;
import model.KhachHang;
import model.TinhToanHoaDon;

/**
 *
 * @author DatIT
 */
public class SapXepHoaDonFrm extends javax.swing.JFrame {

    DefaultTableModel model;
    ArrayList<TinhToanHoaDon> list;
    private int moduleLapBangKe;
    private KhachHang khachHang;
    public SapXepHoaDonFrm() {
        initComponents();
        moduleLapBangKe = 0;
        initTable();
        setLocationRelativeTo(null);
    }
    public SapXepHoaDonFrm(KhachHang khachHang, int moduleLapBangKe) {
        initComponents();
        
        this.moduleLapBangKe = moduleLapBangKe;
        this.khachHang = khachHang;
        btnSXHoten.hide();
        btnSXSoLuong.hide();
        initTable();
        setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTinhToanHoaDon = new javax.swing.JTable();
        btnSXHoten = new javax.swing.JButton();
        btnSXSoLuong = new javax.swing.JButton();
        btnQuayLai = new javax.swing.JButton();
        labTieuDe = new javax.swing.JLabel();
        labSoTien = new javax.swing.JLabel();
        labTieuDeSoLuong = new javax.swing.JLabel();
        labSoLuong = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 255));
        jLabel1.setText("PHẦN MỀM QUẢN LÝ BÁN HÀNG");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Danh sách hóa đơn");

        tblTinhToanHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTinhToanHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTinhToanHoaDonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTinhToanHoaDon);

        btnSXHoten.setText("Sắp xếp theo Họ tên");
        btnSXHoten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSXHotenActionPerformed(evt);
            }
        });

        btnSXSoLuong.setText("Sắp xếp theo số lượng");
        btnSXSoLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSXSoLuongActionPerformed(evt);
            }
        });

        btnQuayLai.setText("Quay lại");
        btnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLaiActionPerformed(evt);
            }
        });

        labTieuDe.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labTieuDe.setText("Tổng tiền phải trả:");

        labSoTien.setText("Số tiền");

        labTieuDeSoLuong.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labTieuDeSoLuong.setText("Tổng số lượng mặt hàng:");

        labSoLuong.setText("Số mặt hàng");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSXHoten, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnSXSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnQuayLai, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 228, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(297, 297, 297))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(221, 221, 221))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(labTieuDeSoLuong, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labTieuDe, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labSoTien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labSoLuong, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labTieuDeSoLuong)
                    .addComponent(labSoLuong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labTieuDe)
                    .addComponent(labSoTien))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSXSoLuong)
                    .addComponent(btnSXHoten)
                    .addComponent(btnQuayLai))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSXHotenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSXHotenActionPerformed
        Collections.sort(list, new Comparator<TinhToanHoaDon>() {
            @Override
            public int compare(TinhToanHoaDon o1, TinhToanHoaDon o2) { 
                int vtTenO1  = ((o1.getKhach().getHoTen()).trim()).lastIndexOf(" ") + 1;
                int vtTenO2 =((o2.getKhach().getHoTen()).trim()).lastIndexOf(" ") + 1;
                return o1.getKhach().getHoTen().substring(vtTenO1).compareTo( o2.getKhach().getHoTen().substring(vtTenO2));
            }
        });
        
        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss dd/MM/YYYY");
        model.setRowCount(0);
        int index = 1;
        for (TinhToanHoaDon tinhToanHoaDon : list) {
            model.addRow(new Object[]{
                index++, tinhToanHoaDon.getId(), tinhToanHoaDon.getKhach().getHoTen(),
                sdf.format( tinhToanHoaDon.getThoiGianMua()), tinhToanHoaDon.getKhuyenMai() + "%", tinhToanHoaDon.getTongSoMatHang()
                ,tinhToanHoaDon.getTongTienPhaiTra()
            });
        }
        model.fireTableDataChanged();
    }//GEN-LAST:event_btnSXHotenActionPerformed

    private void btnSXSoLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSXSoLuongActionPerformed
        
        Collections.sort(list, new Comparator<TinhToanHoaDon>() {
            @Override
            public int compare(TinhToanHoaDon o1, TinhToanHoaDon o2) { 
                return o1.getTongSoMatHang() < o2.getTongSoMatHang() ? 1: -1;
            }
        });
        
        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss dd/MM/YYYY");
        model.setRowCount(0);
        int index = 1;
        for (TinhToanHoaDon tinhToanHoaDon : list) {
            model.addRow(new Object[]{
                index++, tinhToanHoaDon.getId(), tinhToanHoaDon.getKhach().getHoTen(),
                sdf.format( tinhToanHoaDon.getThoiGianMua()), tinhToanHoaDon.getKhuyenMai() + "%", tinhToanHoaDon.getTongSoMatHang()
                ,tinhToanHoaDon.getTongTienPhaiTra()
            });
        }
        model.fireTableDataChanged();
    }//GEN-LAST:event_btnSXSoLuongActionPerformed

    private void btnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaiActionPerformed
        if( moduleLapBangKe != 0){
            (new ChonKhachHangFrm(moduleLapBangKe)).setVisible(true);
            this.dispose();
        }
        else{
            (new TrangChuFrm()).setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnQuayLaiActionPerformed

    private void tblTinhToanHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTinhToanHoaDonMouseClicked
        int selected = tblTinhToanHoaDon.getSelectedRow();
        if( selected >= 0){
            int id = (int) tblTinhToanHoaDon.getValueAt(selected, 1);
            for (TinhToanHoaDon tinhToanHoaDon : list) {
                if( tinhToanHoaDon.getId() == id){
                    ( new ChiTietHoaDonFrm(tinhToanHoaDon, moduleLapBangKe)).setVisible(true);
                    this.dispose();
                }
            }
        }
    }//GEN-LAST:event_tblTinhToanHoaDonMouseClicked

    void initTable(){
        model = new DefaultTableModel();
        list = new ArrayList<>();
        
        // tạo bảng
        String[] colums = new String[]{
            "STT", "Mã đơn hàng", "Tên khách hàng", "Thời gian mua", "Khuyến mãi", "Tổng mặt hàng", "Tổng tiền"
        };
        model.setColumnIdentifiers(colums);
        
        TinhToanHoaDonDAO tthd = new TinhToanHoaDonDAO();
        if( moduleLapBangKe != 0) list = tthd.layTinhToanHoaDon( khachHang);
        else list = tthd.layTinhToanHoaDon();
        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss dd/MM/YYYY");
        
        // đẩy dữ liệu vào bảng
        int index = 1, tongSL = 0;
        float tongTien = 0;
        for (TinhToanHoaDon tinhToanHoaDon : list) {
            model.addRow(new Object[]{
                index++, tinhToanHoaDon.getId(), tinhToanHoaDon.getKhach().getHoTen(),
                sdf.format( tinhToanHoaDon.getThoiGianMua()), tinhToanHoaDon.getKhuyenMai() + "%", tinhToanHoaDon.getTongSoMatHang()
                ,tinhToanHoaDon.getTongTienPhaiTra()
            });
            tongTien += tinhToanHoaDon.getTongTienPhaiTra();
            tongSL += tinhToanHoaDon.getTongSoMatHang();
        }
        tblTinhToanHoaDon.setModel(model);
        
        // set Label 
        if( moduleLapBangKe != 0){
            labSoTien.setText(tongTien+ "");
            labSoLuong.setText( tongSL +"");
        }else{
            labTieuDe.hide();
            labSoTien.hide();
            labSoLuong.hide();
            labTieuDeSoLuong.hide();
        }
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuayLai;
    private javax.swing.JButton btnSXHoten;
    private javax.swing.JButton btnSXSoLuong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labSoLuong;
    private javax.swing.JLabel labSoTien;
    private javax.swing.JLabel labTieuDe;
    private javax.swing.JLabel labTieuDeSoLuong;
    private javax.swing.JTable tblTinhToanHoaDon;
    // End of variables declaration//GEN-END:variables
}
