/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import model.HoaDon;
import model.ViecMuaHang;

/**
 *
 * @author DatIT
 */
public class XuatHoaDonFrm extends javax.swing.JFrame {

    /** Creates new form XuatHoaDonFrm */
    private HoaDon hoaDon;
    
    public XuatHoaDonFrm() {
        initComponents();
        
        setLocationRelativeTo(null);
    }

    public XuatHoaDonFrm(HoaDon hoaDon) {
        initComponents();
        this.hoaDon = hoaDon;
        initTable();
        setLocationRelativeTo(null);
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblViecMuaHang = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        labTongTien = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labTenKhach = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        labThoiGianLap = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labSoLuongSp = new javax.swing.JLabel();
        btnNhapTiep = new javax.swing.JButton();
        btnTrangChu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hóa Đơn");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 255));
        jLabel1.setText("PHẦN MỀM QUẢN LÝ BÁN HÀNG");

        tblViecMuaHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblViecMuaHang);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Tổng tiền phải trả:");

        labTongTien.setText("\"Tiền\"");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Tên khách hàng:");

        labTenKhach.setText("\"Tên Khách\"");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Thời gian lập hóa đơn:");

        labThoiGianLap.setText("Thời gian lập");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Số lượng sản phầm");

        labSoLuongSp.setText("Số lương ");

        btnNhapTiep.setText("Nhập Tiếp Danh Sách");
        btnNhapTiep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapTiepActionPerformed(evt);
            }
        });

        btnTrangChu.setText("Trang Chủ");
        btnTrangChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrangChuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(labTenKhach, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(119, 119, 119)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labThoiGianLap, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(labSoLuongSp, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(labTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(btnNhapTiep, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnTrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(labTenKhach)
                    .addComponent(jLabel6)
                    .addComponent(labThoiGianLap))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(labSoLuongSp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(labTongTien))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNhapTiep)
                    .addComponent(btnTrangChu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNhapTiepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapTiepActionPerformed
        ( new ChonKhachHangFrm()).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnNhapTiepActionPerformed

    private void btnTrangChuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrangChuActionPerformed
        ( new TrangChuFrm()).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTrangChuActionPerformed

    
    private void initTable(){
        
        float tongTien = 0;
        
        // khỏi tạo bảng
        DefaultTableModel model = new DefaultTableModel();
        String[] Colums = new String[]{
            "STT", "MÃ MẶT HÀNG", "TÊN", "ĐƠN GIÁ", "SỐ LƯỢNG", "KHUYẾN MÃI", "THÀNH TIỀN", "GHI CHÚ"
        };
        model.setColumnIdentifiers(Colums);
        
        // lấy dữ liệu vào model
        int index = 1;
        for (ViecMuaHang viecMuaHang : hoaDon.getListVMH()) {
            model.addRow(new Object[]{
                index++, viecMuaHang.getMatHang().getId(), viecMuaHang.getMatHang().getTen(),
                viecMuaHang.getMatHang().getDonGia(), viecMuaHang.getSoLuong(), hoaDon.getKhuyenMai()*100 +"%",
                viecMuaHang.getThanhTien(), viecMuaHang.getGhiChu()
            });
            tongTien += viecMuaHang.getThanhTien();
        }
        tblViecMuaHang.setModel(model);
        
        // khởi tạo thông tin
        labTenKhach.setText(hoaDon.getKhach().getHoTen());
        labSoLuongSp.setText("" + hoaDon.getListVMH().size());
        labTongTien.setText("" + tongTien);
        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss dd/MM/YYYY");
        labThoiGianLap.setText( sdf.format( hoaDon.getThoiGianMua()));
        
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNhapTiep;
    private javax.swing.JButton btnTrangChu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labSoLuongSp;
    private javax.swing.JLabel labTenKhach;
    private javax.swing.JLabel labThoiGianLap;
    private javax.swing.JLabel labTongTien;
    private javax.swing.JTable tblViecMuaHang;
    // End of variables declaration//GEN-END:variables

}
